Add litre gasoline-equivalent conversion
IAMconsortium/units pull request #27
Opened 2021-07-20 13:16 UTC by francescolovat

This PR addresses the addition of the energy unit conversion of `litres of gasoline-equivalent` (`Lge`). These units are used to represent quantities in [this GFEI report](https://theicct.org/sites/default/files/publications/GFEI_WP19_Final_V3_Web.pdf), from which we happened to received some data.

How to review:
- Check that the following commands work in your own machine:
```
from iam_units import registry
qty = registry('33.5 MJ')
qty.to('Lge')
1.0 <Unit('Lge')>
```

2021-07-20 15:25 UTC, khaeru requested changes
Please include in the comment a specific, locatable/citable source for the added value.

2021-07-20 15:49 UTC, francescolovat commented
@khaeru thanks! I've just added it. Please feel free to merge it when tests will pass!

2021-07-21 09:07 UTC, khaeru approved these changes
Excellent, thanks.

As discussed in #24, conversion from [volume] to [energy] could someday be implemented with a context. At that point we could decide whether to keep this entry or remove it.

2021-07-21 09:07 UTC, merged

2021-07-21 09:10 UTC, khaeru commented
@francescolovat sorry, but I realized belatedly that definitions.txt is organized in sections and this, being energy-related, should have gone in the "Energy" section, rather than at the very bottom of the file.

I will move the lines as I prepare a new release.

2021-07-21 09:22 UTC, francescolovat commented
Thanks for making it even clearer, @khaeru !